export const csesData = [
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1068",
    number: "1",
    solved: "False",
    title: "Weird Algorithm",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1083",
    number: "2",
    solved: "False",
    title: "Missing Number",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1069",
    number: "3",
    solved: "False",
    title: "Repetitions",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1094",
    number: "4",
    solved: "False",
    title: "Increasing Array",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1070",
    number: "5",
    solved: "False",
    title: "Permutations",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1071",
    number: "6",
    solved: "False",
    title: "Number Spiral",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1072",
    number: "7",
    solved: "False",
    title: "Two Knights",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1092",
    number: "8",
    solved: "False",
    title: "Two Sets",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1617",
    number: "9",
    solved: "False",
    title: "Bit Strings",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1618",
    number: "10",
    solved: "False",
    title: "Trailing Zeros",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1754",
    number: "11",
    solved: "False",
    title: "Coin Piles",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1755",
    number: "12",
    solved: "False",
    title: "Palindrome Reorder",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2205",
    number: "13",
    solved: "False",
    title: "Gray Code",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2165",
    number: "14",
    solved: "False",
    title: "Tower of Hanoi",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1622",
    number: "15",
    solved: "False",
    title: "Creating Strings",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1623",
    number: "16",
    solved: "False",
    title: "Apple Division",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1624",
    number: "17",
    solved: "False",
    title: "Chessboard and Queens",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2431",
    number: "18",
    solved: "False",
    title: "Digit Queries",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1625",
    number: "19",
    solved: "False",
    title: "Grid Paths",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1621",
    number: "20",
    solved: "False",
    title: "Distinct Numbers",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1084",
    number: "21",
    solved: "False",
    title: "Apartments",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1090",
    number: "22",
    solved: "False",
    title: "Ferris Wheel",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1091",
    number: "23",
    solved: "False",
    title: "Concert Tickets",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1619",
    number: "24",
    solved: "False",
    title: "Restaurant Customers",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1629",
    number: "25",
    solved: "False",
    title: "Movie Festival",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1640",
    number: "26",
    solved: "False",
    title: "Sum of Two Values",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1643",
    number: "27",
    solved: "False",
    title: "Maximum Subarray Sum",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1074",
    number: "28",
    solved: "False",
    title: "Stick Lengths",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2183",
    number: "29",
    solved: "False",
    title: "Missing Coin Sum",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2216",
    number: "30",
    solved: "False",
    title: "Collecting Numbers",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2217",
    number: "31",
    solved: "False",
    title: "Collecting Numbers II",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1141",
    number: "32",
    solved: "False",
    title: "Playlist",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1073",
    number: "33",
    solved: "False",
    title: "Towers",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1163",
    number: "34",
    solved: "False",
    title: "Traffic Lights",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2162",
    number: "35",
    solved: "False",
    title: "Josephus Problem I",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2163",
    number: "36",
    solved: "False",
    title: "Josephus Problem II",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2168",
    number: "37",
    solved: "False",
    title: "Nested Ranges Check",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2169",
    number: "38",
    solved: "False",
    title: "Nested Ranges Count",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1164",
    number: "39",
    solved: "False",
    title: "Room Allocation",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1620",
    number: "40",
    solved: "False",
    title: "Factory Machines",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1630",
    number: "41",
    solved: "False",
    title: "Tasks and Deadlines",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1631",
    number: "42",
    solved: "False",
    title: "Reading Books",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1641",
    number: "43",
    solved: "False",
    title: "Sum of Three Values",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1642",
    number: "44",
    solved: "False",
    title: "Sum of Four Values",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1645",
    number: "45",
    solved: "False",
    title: "Nearest Smaller Values",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1660",
    number: "46",
    solved: "False",
    title: "Subarray Sums I",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1661",
    number: "47",
    solved: "False",
    title: "Subarray Sums II",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1662",
    number: "48",
    solved: "False",
    title: "Subarray Divisibility",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2428",
    number: "49",
    solved: "False",
    title: "Subarray Distinct Values",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1085",
    number: "50",
    solved: "False",
    title: "Array Division",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1076",
    number: "51",
    solved: "False",
    title: "Sliding Median",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1077",
    number: "52",
    solved: "False",
    title: "Sliding Cost",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1632",
    number: "53",
    solved: "False",
    title: "Movie Festival II",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1644",
    number: "54",
    solved: "False",
    title: "Maximum Subarray Sum II",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1633",
    number: "55",
    solved: "False",
    title: "Dice Combinations",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1634",
    number: "56",
    solved: "False",
    title: "Minimizing Coins",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1635",
    number: "57",
    solved: "False",
    title: "Coin Combinations I",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1636",
    number: "58",
    solved: "False",
    title: "Coin Combinations II",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1637",
    number: "59",
    solved: "False",
    title: "Removing Digits",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1638",
    number: "60",
    solved: "False",
    title: "Grid Paths",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1158",
    number: "61",
    solved: "False",
    title: "Book Shop",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1746",
    number: "62",
    solved: "False",
    title: "Array Description",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2413",
    number: "63",
    solved: "False",
    title: "Counting Towers",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1639",
    number: "64",
    solved: "False",
    title: "Edit Distance",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1744",
    number: "65",
    solved: "False",
    title: "Rectangle Cutting",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1745",
    number: "66",
    solved: "False",
    title: "Money Sums",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1097",
    number: "67",
    solved: "False",
    title: "Removal Game",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1093",
    number: "68",
    solved: "False",
    title: "Two Sets II",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1145",
    number: "69",
    solved: "False",
    title: "Increasing Subsequence",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1140",
    number: "70",
    solved: "False",
    title: "Projects",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1653",
    number: "71",
    solved: "False",
    title: "Elevator Rides",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2181",
    number: "72",
    solved: "False",
    title: "Counting Tilings",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2220",
    number: "73",
    solved: "False",
    title: "Counting Numbers",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1192",
    number: "74",
    solved: "False",
    title: "Counting Rooms",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1193",
    number: "75",
    solved: "False",
    title: "Labyrinth",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1666",
    number: "76",
    solved: "False",
    title: "Building Roads",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1667",
    number: "77",
    solved: "False",
    title: "Message Route",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1668",
    number: "78",
    solved: "False",
    title: "Building Teams",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1669",
    number: "79",
    solved: "False",
    title: "Round Trip",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1194",
    number: "80",
    solved: "False",
    title: "Monsters",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1671",
    number: "81",
    solved: "False",
    title: "Shortest Routes I",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1672",
    number: "82",
    solved: "False",
    title: "Shortest Routes II",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1673",
    number: "83",
    solved: "False",
    title: "High Score",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1195",
    number: "84",
    solved: "False",
    title: "Flight Discount",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1197",
    number: "85",
    solved: "False",
    title: "Cycle Finding",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1196",
    number: "86",
    solved: "False",
    title: "Flight Routes",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1678",
    number: "87",
    solved: "False",
    title: "Round Trip II",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1679",
    number: "88",
    solved: "False",
    title: "Course Schedule",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1680",
    number: "89",
    solved: "False",
    title: "Longest Flight Route",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1681",
    number: "90",
    solved: "False",
    title: "Game Routes",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1202",
    number: "91",
    solved: "False",
    title: "Investigation",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1750",
    number: "92",
    solved: "False",
    title: "Planets Queries I",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1160",
    number: "93",
    solved: "False",
    title: "Planets Queries II",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1751",
    number: "94",
    solved: "False",
    title: "Planets Cycles",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1675",
    number: "95",
    solved: "False",
    title: "Road Reparation",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1676",
    number: "96",
    solved: "False",
    title: "Road Construction",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1682",
    number: "97",
    solved: "False",
    title: "Flight Routes Check",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1683",
    number: "98",
    solved: "False",
    title: "Planets and Kingdoms",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1684",
    number: "99",
    solved: "False",
    title: "Giant Pizza",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1686",
    number: "100",
    solved: "False",
    title: "Coin Collector",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1691",
    number: "101",
    solved: "False",
    title: "Mail Delivery",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1692",
    number: "102",
    solved: "False",
    title: "De Bruijn Sequence",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1693",
    number: "103",
    solved: "False",
    title: "Teleporters Path",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1690",
    number: "104",
    solved: "False",
    title: "Hamiltonian Flights",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1689",
    number: "105",
    solved: "False",
    title: "Knight's Tour",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1694",
    number: "106",
    solved: "False",
    title: "Download Speed",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1695",
    number: "107",
    solved: "False",
    title: "Police Chase",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1696",
    number: "108",
    solved: "False",
    title: "School Dance",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1711",
    number: "109",
    solved: "False",
    title: "Distinct Routes",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1646",
    number: "110",
    solved: "False",
    title: "Static Range Sum Queries",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1647",
    number: "111",
    solved: "False",
    title: "Static Range Minimum Queries",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1648",
    number: "112",
    solved: "False",
    title: "Dynamic Range Sum Queries",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1649",
    number: "113",
    solved: "False",
    title: "Dynamic Range Minimum Queries",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1650",
    number: "114",
    solved: "False",
    title: "Range Xor Queries",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1651",
    number: "115",
    solved: "False",
    title: "Range Update Queries",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1652",
    number: "116",
    solved: "False",
    title: "Forest Queries",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1143",
    number: "117",
    solved: "False",
    title: "Hotel Queries",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1749",
    number: "118",
    solved: "False",
    title: "List Removals",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1144",
    number: "119",
    solved: "False",
    title: "Salary Queries",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2166",
    number: "120",
    solved: "False",
    title: "Prefix Sum Queries",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2206",
    number: "121",
    solved: "False",
    title: "Pizzeria Queries",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1190",
    number: "122",
    solved: "False",
    title: "Subarray Sum Queries",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1734",
    number: "123",
    solved: "False",
    title: "Distinct Values Queries",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2416",
    number: "124",
    solved: "False",
    title: "Increasing Array Queries",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1739",
    number: "125",
    solved: "False",
    title: "Forest Queries II",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1735",
    number: "126",
    solved: "False",
    title: "Range Updates and Sums",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1736",
    number: "127",
    solved: "False",
    title: "Polynomial Queries",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1737",
    number: "128",
    solved: "False",
    title: "Range Queries and Copies",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1674",
    number: "129",
    solved: "False",
    title: "Subordinates",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1130",
    number: "130",
    solved: "False",
    title: "Tree Matching",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1131",
    number: "131",
    solved: "False",
    title: "Tree Diameter",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1132",
    number: "132",
    solved: "False",
    title: "Tree Distances I",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1133",
    number: "133",
    solved: "False",
    title: "Tree Distances II",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1687",
    number: "134",
    solved: "False",
    title: "Company Queries I",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1688",
    number: "135",
    solved: "False",
    title: "Company Queries II",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1135",
    number: "136",
    solved: "False",
    title: "Distance Queries",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1136",
    number: "137",
    solved: "False",
    title: "Counting Paths",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1137",
    number: "138",
    solved: "False",
    title: "Subtree Queries",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1138",
    number: "139",
    solved: "False",
    title: "Path Queries",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2134",
    number: "140",
    solved: "False",
    title: "Path Queries II",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1139",
    number: "141",
    solved: "False",
    title: "Distinct Colors",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2079",
    number: "142",
    solved: "False",
    title: "Finding a Centroid",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2080",
    number: "143",
    solved: "False",
    title: "Fixed-Length Paths I",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2081",
    number: "144",
    solved: "False",
    title: "Fixed-Length Paths II",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2164",
    number: "145",
    solved: "False",
    title: "Josephus Queries",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1095",
    number: "146",
    solved: "False",
    title: "Exponentiation",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1712",
    number: "147",
    solved: "False",
    title: "Exponentiation II",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1713",
    number: "148",
    solved: "False",
    title: "Counting Divisors",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1081",
    number: "149",
    solved: "False",
    title: "Common Divisors",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1082",
    number: "150",
    solved: "False",
    title: "Sum of Divisors",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2182",
    number: "151",
    solved: "False",
    title: "Divisor Analysis",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2185",
    number: "152",
    solved: "False",
    title: "Prime Multiples",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2417",
    number: "153",
    solved: "False",
    title: "Counting Coprime Pairs",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1079",
    number: "154",
    solved: "False",
    title: "Binomial Coefficients",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1715",
    number: "155",
    solved: "False",
    title: "Creating Strings II",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1716",
    number: "156",
    solved: "False",
    title: "Distributing Apples",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1717",
    number: "157",
    solved: "False",
    title: "Christmas Party",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2064",
    number: "158",
    solved: "False",
    title: "Bracket Sequences I",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2187",
    number: "159",
    solved: "False",
    title: "Bracket Sequences II",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2209",
    number: "160",
    solved: "False",
    title: "Counting Necklaces",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2210",
    number: "161",
    solved: "False",
    title: "Counting Grids",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1722",
    number: "162",
    solved: "False",
    title: "Fibonacci Numbers",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1096",
    number: "163",
    solved: "False",
    title: "Throwing Dice",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1723",
    number: "164",
    solved: "False",
    title: "Graph Paths I",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1724",
    number: "165",
    solved: "False",
    title: "Graph Paths II",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1725",
    number: "166",
    solved: "False",
    title: "Dice Probability",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1726",
    number: "167",
    solved: "False",
    title: "Moving Robots",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1727",
    number: "168",
    solved: "False",
    title: "Candy Lottery",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1728",
    number: "169",
    solved: "False",
    title: "Inversion Probability",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1729",
    number: "170",
    solved: "False",
    title: "Stick Game",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1730",
    number: "171",
    solved: "False",
    title: "Nim Game I",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1098",
    number: "172",
    solved: "False",
    title: "Nim Game II",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1099",
    number: "173",
    solved: "False",
    title: "Stair Game",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2207",
    number: "174",
    solved: "False",
    title: "Grundy's Game",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2208",
    number: "175",
    solved: "False",
    title: "Another Game",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1731",
    number: "176",
    solved: "False",
    title: "Word Combinations",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1753",
    number: "177",
    solved: "False",
    title: "String Matching",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1732",
    number: "178",
    solved: "False",
    title: "Finding Borders",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1733",
    number: "179",
    solved: "False",
    title: "Finding Periods",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1110",
    number: "180",
    solved: "False",
    title: "Minimal Rotation",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1111",
    number: "181",
    solved: "False",
    title: "Longest Palindrome",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1112",
    number: "182",
    solved: "False",
    title: "Required Substring",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2420",
    number: "183",
    solved: "False",
    title: "Palindrome Queries",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2102",
    number: "184",
    solved: "False",
    title: "Finding Patterns",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2103",
    number: "185",
    solved: "False",
    title: "Counting Patterns",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2104",
    number: "186",
    solved: "False",
    title: "Pattern Positions",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2105",
    number: "187",
    solved: "False",
    title: "Distinct Substrings",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2106",
    number: "188",
    solved: "False",
    title: "Repeating Substring",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2107",
    number: "189",
    solved: "False",
    title: "String Functions",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2108",
    number: "190",
    solved: "False",
    title: "Substring Order I",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2109",
    number: "191",
    solved: "False",
    title: "Substring Order II",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2110",
    number: "192",
    solved: "False",
    title: "Substring Distribution",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2189",
    number: "193",
    solved: "False",
    title: "Point Location Test",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2190",
    number: "194",
    solved: "False",
    title: "Line Segment Intersection",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2191",
    number: "195",
    solved: "False",
    title: "Polygon Area",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2192",
    number: "196",
    solved: "False",
    title: "Point in Polygon",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2193",
    number: "197",
    solved: "False",
    title: "Polygon Lattice Points",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2194",
    number: "198",
    solved: "False",
    title: "Minimum Euclidean Distance",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2195",
    number: "199",
    solved: "False",
    title: "Convex Hull",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1628",
    number: "200",
    solved: "False",
    title: "Meet in the Middle",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2136",
    number: "201",
    solved: "False",
    title: "Hamming Distance",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2137",
    number: "202",
    solved: "False",
    title: "Beautiful Subgrids",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2138",
    number: "203",
    solved: "False",
    title: "Reachable Nodes",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2143",
    number: "204",
    solved: "False",
    title: "Reachability Queries",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2072",
    number: "205",
    solved: "False",
    title: "Cut and Paste",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2073",
    number: "206",
    solved: "False",
    title: "Substring Reversals",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2074",
    number: "207",
    solved: "False",
    title: "Reversals and Sums",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2076",
    number: "208",
    solved: "False",
    title: "Necessary Roads",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2077",
    number: "209",
    solved: "False",
    title: "Necessary Cities",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2078",
    number: "210",
    solved: "False",
    title: "Eulerian Subgraphs",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2084",
    number: "211",
    solved: "False",
    title: "Monster Game I",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2085",
    number: "212",
    solved: "False",
    title: "Monster Game II",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2086",
    number: "213",
    solved: "False",
    title: "Subarray Squares",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2087",
    number: "214",
    solved: "False",
    title: "Houses and Schools",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2088",
    number: "215",
    solved: "False",
    title: "Knuth Division",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2111",
    number: "216",
    solved: "False",
    title: "Apples and Bananas",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2112",
    number: "217",
    solved: "False",
    title: "One Bit Positions",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2113",
    number: "218",
    solved: "False",
    title: "Signal Processing",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2101",
    number: "219",
    solved: "False",
    title: "New Roads Queries",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2133",
    number: "220",
    solved: "False",
    title: "Dynamic Connectivity",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2121",
    number: "221",
    solved: "False",
    title: "Parcel Delivery",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2129",
    number: "222",
    solved: "False",
    title: "Task Assignment",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2130",
    number: "223",
    solved: "False",
    title: "Distinct Routes II",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1087",
    number: "224",
    solved: "False",
    title: "Shortest Subsequence",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1146",
    number: "225",
    solved: "False",
    title: "Counting Bits",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1670",
    number: "226",
    solved: "False",
    title: "Swap Game",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1134",
    number: "227",
    solved: "False",
    title: "Pr\u00fcfer Code",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1756",
    number: "228",
    solved: "False",
    title: "Acyclic Graph Edges",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2177",
    number: "229",
    solved: "False",
    title: "Strongly Connected Edges",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2179",
    number: "230",
    solved: "False",
    title: "Even Outdegree Edges",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2422",
    number: "231",
    solved: "False",
    title: "Multiplication Table",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1142",
    number: "232",
    solved: "False",
    title: "Advertisement",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2186",
    number: "233",
    solved: "False",
    title: "Special Substrings",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2229",
    number: "234",
    solved: "False",
    title: "Permutation Inversions",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1655",
    number: "235",
    solved: "False",
    title: "Maximum Xor Subarray",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1664",
    number: "236",
    solved: "False",
    title: "Movie Festival Queries",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1697",
    number: "237",
    solved: "False",
    title: "Chess Tournament",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1702",
    number: "238",
    solved: "False",
    title: "Tree Traversals",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1704",
    number: "239",
    solved: "False",
    title: "Network Renovation",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1707",
    number: "240",
    solved: "False",
    title: "Graph Girth",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1740",
    number: "241",
    solved: "False",
    title: "Intersection Points",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2214",
    number: "242",
    solved: "False",
    title: "Inverse Inversions",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2215",
    number: "243",
    solved: "False",
    title: "Monotone Subsequences",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1743",
    number: "244",
    solved: "False",
    title: "String Reorder",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2425",
    number: "245",
    solved: "False",
    title: "Stack Weights",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1747",
    number: "246",
    solved: "False",
    title: "Pyramid Array",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1748",
    number: "247",
    solved: "False",
    title: "Increasing Subsequence II",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1149",
    number: "248",
    solved: "False",
    title: "String Removals",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1188",
    number: "249",
    solved: "False",
    title: "Bit Inversions",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2419",
    number: "250",
    solved: "False",
    title: "Xor Pyramid",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1086",
    number: "251",
    solved: "False",
    title: "Writing Numbers",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1113",
    number: "252",
    solved: "False",
    title: "String Transform",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2427",
    number: "253",
    solved: "False",
    title: "Letter Pair Move Game",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1147",
    number: "254",
    solved: "False",
    title: "Maximum Building I",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1162",
    number: "255",
    solved: "False",
    title: "Sorting Methods",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1191",
    number: "256",
    solved: "False",
    title: "Cyclic Array",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2414",
    number: "257",
    solved: "False",
    title: "List of Sums",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2132",
    number: "258",
    solved: "False",
    title: "Increasing Array II",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1189",
    number: "259",
    solved: "False",
    title: "Food Division",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1654",
    number: "260",
    solved: "False",
    title: "Bit Problem",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1698",
    number: "261",
    solved: "False",
    title: "Swap Round Sorting",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2430",
    number: "262",
    solved: "False",
    title: "Binary Subsequences",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1700",
    number: "263",
    solved: "False",
    title: "Tree Isomorphism I",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2228",
    number: "264",
    solved: "False",
    title: "Counting Sequences",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1703",
    number: "265",
    solved: "False",
    title: "Critical Cities",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1706",
    number: "266",
    solved: "False",
    title: "School Excursion",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1709",
    number: "267",
    solved: "False",
    title: "Coin Grid",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1742",
    number: "268",
    solved: "False",
    title: "Robot Path",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2426",
    number: "269",
    solved: "False",
    title: "Programmers and Artists",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1757",
    number: "270",
    solved: "False",
    title: "Course Schedule II",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2174",
    number: "271",
    solved: "False",
    title: "Removing Digits II",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2180",
    number: "272",
    solved: "False",
    title: "Coin Arrangement",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2176",
    number: "273",
    solved: "False",
    title: "Counting Bishops",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2432",
    number: "274",
    solved: "False",
    title: "Grid Puzzle I",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2131",
    number: "275",
    solved: "False",
    title: "Grid Puzzle II",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1080",
    number: "276",
    solved: "False",
    title: "Empty String",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1078",
    number: "277",
    solved: "False",
    title: "Grid Paths",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2115",
    number: "278",
    solved: "False",
    title: "Bit Substrings",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2075",
    number: "279",
    solved: "False",
    title: "Reversal Sorting",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2421",
    number: "280",
    solved: "False",
    title: "Counting Reorders",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1159",
    number: "281",
    solved: "False",
    title: "Book Shop II",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1677",
    number: "282",
    solved: "False",
    title: "Network Breakdown",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1203",
    number: "283",
    solved: "False",
    title: "Visiting Cities",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2184",
    number: "284",
    solved: "False",
    title: "Missing Coin Sum Queries",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1157",
    number: "285",
    solved: "False",
    title: "Number Grid",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1148",
    number: "286",
    solved: "False",
    title: "Maximum Building II",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2423",
    number: "287",
    solved: "False",
    title: "Filling Trominos",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1161",
    number: "288",
    solved: "False",
    title: "Stick Divisions",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1665",
    number: "289",
    solved: "False",
    title: "Coding Company",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1699",
    number: "290",
    solved: "False",
    title: "Flight Route Requests",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2402",
    number: "291",
    solved: "False",
    title: "Two Stacks Sorting",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1701",
    number: "292",
    solved: "False",
    title: "Tree Isomorphism II",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1705",
    number: "293",
    solved: "False",
    title: "Forbidden Cities",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1741",
    number: "294",
    solved: "False",
    title: "Area of Rectangles",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2429",
    number: "295",
    solved: "False",
    title: "Grid Completion",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1752",
    number: "296",
    solved: "False",
    title: "Creating Offices",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1075",
    number: "297",
    solved: "False",
    title: "Permutations II",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2415",
    number: "298",
    solved: "False",
    title: "Functional Graph Distribution",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/1685",
    number: "299",
    solved: "False",
    title: "New Flight Routes",
  },
  {
    difficulty: null,
    link: "https://cses.fi/problemset/task/2418",
    number: "300",
    solved: "False",
    title: "Grid Path Construction",
  },
];
